### ISSUE TITLE
TypeError: undefined is not a function (near '..._reactNativeSweetAlert.default.showAlert...')

### ISSUE THREAD

**Issue by glasje** [acaziasoftcom/react-native-sweet-alert#10]
I am implemented the library but when entering the module I get the following error (attached image).
I am using two test devices (iphone and android) but in both the same error comes out.
![whatsapp image 2019-01-29 at 11 55 54](https://user-images.githubusercontent.com/34929785/51916959-34045100-23bd-11e9-827a-08075424afd9.jpeg)
Attached image with the code.
![image](https://user-images.githubusercontent.com/34929785/51917075-7c237380-23bd-11e9-878d-dfa938354105.png)

**Comment by Doko-Demo-Doa** [comment]
Hello @glasje 
Thanks for using the library. There was a mistake in README file, I have updated it.

**Comment by masesisaac** [comment]
Android support was broken, ShowAlertWithOptions only supported on IOS
