### ISSUE TITLE
Android support was broken, ShowAlertWithOptions only supported on IOS

### ISSUE THREAD

**Issue by masesisaac** [acaziasoftcom/react-native-sweet-alert#11]
Android support was broken, ShowAlertWithOptions only supported on IOS

_Originally posted by @masesisaac in https://github.com/acaziasoftcom/react-native-sweet-alert/issues/10#issuecomment-458823055_

**Comment by sajadabasi** [comment]
I fixed this issue and created a pull request

**Comment by AbhaySoningra** [comment]
Is this fix merged? I still have the same issue.

**Comment by sajadabasi** [comment]
not yet

**Comment by Doko-Demo-Doa** [comment]
I have combined the code and released new package version. Thank you everyone.

**Comment by AbhaySoningra** [comment]
Thank you for the quick action 👍 :)

**Comment by AbhaySoningra** [comment]
Hi Doko,
Have we removed the capability of alerts with yes/no options and their callbacks from this for Android?

**Comment by Doko-Demo-Doa** [comment]
I think... not. Because I haven't touched the lib for a while. Let me do a quick check.
